main: de.constructcraft.main.Main
version: 0.1
name: ConstructCraft

commands:
  goto:
    #usage: /<command> [player] / [x] [y] [z]
    description: Teleportiert dich zu dem gewünschten Ort.

  cc:
    #usage: /<command> [pos1/pos2]
    description: Speichert oder lädt ein Gebäude, die zuvor gespeichert wurden.